services:
  - type: web
    name: sis414-productos
    runtime: docker
    plan: free
    healthCheckPath: /health
    envVars:
      - key: DB_URL
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false

